vinna/company/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^new$', CreateCompanyView.as_view(), name='create'),
    url(r'^owned$', OwnedCompanyView.as_view(), name='owned'),
]

vinna/job/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^create/$', CreateJobView.as_view(), name='create_hiring'),
]

vinna/userprofile/urls.py
from django.conf.urls import url
from .views import UpdateAccount


urlpatterns = [
    url(r'^(?P<pk>\d+)$', UpdateAccount.as_view(), name='update'),
]

vinna/vinna/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url, patterns
from django.contrib import admin
from .views import HomepageView

urlpatterns = patterns('',
                       url(r'^$', HomepageView.as_view(), name='homepage'),
                       url(r'^admin/', include(admin.site.urls)),
                       url('', include(
                           'social.apps.django_app.urls', namespace='social')),
                       url('', include(
                           'django.contrib.auth.urls', namespace='auth')),
                       url(r'^account/',
                           include('userprofile.urls', namespace='profile')),
                       url(r'^company/',
                           include('company.urls', namespace='company')),
                       url(r'^job/', include('job.urls', namespace='job')),
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinna/job/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from company.models import Company
# Create your models here.


class JobCategory(models.Model):

    """Sets Of Job Categories For Hiring Classification Purposes"""

    name = models.CharField('Job Title', max_length=255)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Job Category'
        verbose_name_plural = 'Job Categories'


class JobExperience(models.Model):

    """Sets Of Job Experience For Hiring Classification Purposes"""

    name = models.CharField(max_length=200)
    description = models.TextField()
    color_legend = models.CharField('Legend Color', max_length=10)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Job Experience'
        verbose_name_plural = 'Job Experiences'


class JobType(models.Model):

    """Sets Of Job Type for Hiring Classification Purposes"""

    name = models.CharField(max_length=200)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Job Type'
        verbose_name_plural = 'Job Types'


class Profession(models.Model):

    """Sets Of Job Type for Hiring Classification Purposes"""

    name = models.CharField(max_length=200)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Profession'
        verbose_name_plural = 'Professions'


class Hiring(models.Model):

    """Serves As A Hiring Form Created By Companies"""

    company = models.ForeignKey(Company)
    title = models.CharField(max_length=200)
    description = models.TextField()
    requirement = models.TextField()
    timestamp = models.DateTimeField('Posted', auto_now_add=True)
    due = models.DateTimeField('Due Date')
    status = models.BooleanField(default=True)
    category = models.ForeignKey(JobCategory)
    job_experience_required = models.ForeignKey(JobExperience)
    job_type = models.ForeignKey(JobType, default=None, blank=True)
    profession = models.ForeignKey(
        Profession, default=None, blank=True)

    def __unicode__(self):
        return self.title + " by " + self.company.__str__()

    @property
    def valid_for_hiring(self):
        now = timezone.now() - datetime.timedelta(days=1)
        return now <= self.due

    class Meta:
        verbose_name = 'Hiring'
        verbose_name_plural = 'Hirings'


class Application(models.Model):

    """
    Serves as a form that a user has to obtain
    before applying to any given job advertisement
    """

    owner = models.ForeignKey(User)
    hiringform = models.ForeignKey(Hiring)
    essay = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __unicode__(self):
        return self.owner.__str__()

    def get_status(self):
        return self.status
    get_status.boolean = True

vinna/job/forms.py
from django import forms
from models import *


class CreateHiringForm(forms.ModelForm):

    """Form For Creating A New Hiring(s)"""

    class Meta:
        model = Hiring
        exclude = ('company', 'status',)

vinna/job/views.py
from django.views import generic
from .models import *
from .forms import CreateHiringForm
# Create your views here.


class CreateJobView(generic.CreateView):
    form_class = CreateHiringForm
    template_name = 'Hiring_Create_View.html'

vinna/job/templates/Hiring_Create_View.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ page_title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
	</head>
	<body>
		<style>
            /* FOR LINKS */
           a{
                text-decoration:none !important;
                font-size: 20px;
            }
            big{
            float: center;
            }

            body {
                background-color: #ABB7B7;
                margin-top:75px;
            }
            /*  N A V  B A R  */
            #navi{
                color:#00000;
            }
            #comp{
                font-size:30px;
                font-family: 'Ubuntu Medium';
                margin-left: 40px;
            }

            #logo{
                height:120%;
            }

            #icon{
                margin-top: 5px;
                margin-bottom:-5px;
                margin-left: 5px;
                margin-right: -20px;
                height:30px;
            }
            #icon2{
                margin-top: 10px;
                margin-right: 30px;
                margin-left: 20px;
                height:30px;
            }
            /*     H O M E  P A G E   */

            .img-responsive{
                display: inline-block;
                max-height: 100%;
                margin-right: -40px;
            }

            #front{
                margin-top: 100px;
                color:#112233;
            }
            #smile{
                margin-top:100px;
                color:#00000;
            }
            #player{
                margin-bottom: -100px;
            }
            #about{
                background: #2C3E50;
                margin-top: 100px;          
            }
            .marketing{
                width: auto;
            }

            /*    T E X T  C O L O R S   */
            .text-white{
                color: #FFFFFF !important;
            }
            .text-black{
                color: #000000 !important;
            }
            .text-red{
                color: #e74c3c !important
            }
            .text-green{
                color: #2ecc71 !important
            }
            .profile_image{
                border:1px solid white;
                width:150px;
                height: 150px;
            }
		</style>
		<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand header" href="{% url 'homepage' %}"><img id = "logo" src = "{% static 'photos/logo2.1.png' %}"/></a>
                </div>
                <div class ="bar">
                    <div id="navbar" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% if user and user.is_authenticated %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        Hello <span class="text-capitalize">{{ user.get_full_name|default:user.username }}</span>! <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{% url 'profile:update' user.id %}">Account</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'auth:logout' %}?next={% url 'homepage' %}">Logout</a>
                                        </li>
                                    </ul>
                                </li>
                                {% if user.profile.is_employer %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        COMPANY</span> <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        {% if not user.profile.User_Created_A_Company %}
                                        <li>
                                            <a href="{% url 'company:create' %}">Add A Company</a>
                                        </li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url 'company:owned' %}">View Company</a>
                                        </li>
                                        <li class="active">
                                            <a href="{% url 'job:create_hiring' %}">Create Hiring Form</a>
                                        </li>
                                        <li>
                                            <a href="">Hiring Forms</a>
                                        </li>
                                         <li>
                                            <a href="">View Job List</a>
                                        </li>
                                        <li>
                                            <a href="">View Application Form</a><br/>
                                        </li>
                                    </ul>
                                </li>
                                {% endif %}
                            {% else %}                               
                                <div id="navbar" class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav navbar-right">
                                        <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
                                        <img id ="icon" src="{% static 'photos/fb2.jpg' %}" />
                                        <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">
                                        <img id ="icon2" src="{% static 'photos/g+2.jpg' %}" /></a>                  
                                    </ul>
                                </div>                                   
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
		<div class="container">
	        <div class="row">
	            <div class="col-xs-12 col-md-8 col-md-offset-2">
	                <div class="center-block">
	                    <form method="POST" enctype="multipart/form-data">
	                        {% csrf_token %}
	                        {{ form.as_p }}
	                        <input class="btn btn-block btn-success" type="submit" value="Create"/>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script>
            $(document).ready(function(){
                $('[data-toggle="tooltip"]').tooltip()
                $('.popovers').popover()
            })
        </script>
	</body>
</html>